parameters:
    webservice_user_provider.class: PurpleNeve\ControlPanelBundle\Security\User\WebserviceUserProvider

services:
    webservice_user_provider:
        class: "%webservice_user_provider.class%"
        arguments: ['@service_container']