control_panel:
    resource: "@ControlPanelBundle/Resources/config/routing.yml"
    prefix:   /

client_area:
    resource: "@ClientAreaBundle/Resources/config/routing.yml"
    prefix:   /client/

frontend:
    resource: "@FrontendBundle/Resources/config/routing.yml"
    prefix:   /

