security:
    encoders:
        PurpleNeve\ControlPanelBundle\Security\User\WebserviceUser:
            algorithm: sha512
            encode_as_base64: false
            iterations: 1

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        webservice_userprovider:
            id: webservice_user_provider

    firewalls:
        control_panel_login:
            pattern: ^/cp/login$
            anonymous: ~

        control_panel:
            pattern: ^/cp/
            provider: webservice_userprovider
            form_login:
                check_path: /cp/login/process
                login_path: /cp/login
                default_target_path: /cp/dashboard
            logout:
                path: /cp/logout
                target: /

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

    access_control:
        - { path: ^/cp/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/client/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/cp/, roles: ROLE_ADMIN }
        - { path: ^/client/, roles: ROLE_CLIENT }
